Repository neurobagel/annotation-tool, pull requests merged in 2025-03, with the labels that each got.

#63 [MNT] Set up devtools for zustand
  src/stores/data.ts
  src/stores/view.ts
Labels: pr-internal

#59 [ENH] Implemented `ColumnAnnotationCard` component
  configs/default.json
  cypress/component/ColumAnnotation.cy.tsx
  cypress/component/ColumnAnnotationCard.cy.tsx
  cypress/component/DescriptionEditor.cy.tsx
  src/components/ColumnAnnotation.tsx
  src/components/ColumnAnnotationCard.tsx
  src/components/DescriptionEditor.tsx
  src/components/UploadCard.tsx
  src/stores/data.test.ts
  src/stores/data.ts
  src/theme.ts
  src/utils/mocks.ts
  src/utils/types.ts
Labels: pr-minor

#61 [ENH] Implemented UI and logic for `Download` view
  cypress/component/CustomDataDictionaryPreview.cy.tsx
  cypress/component/DataDictionaryPreview.cy.tsx
  cypress/component/Download.cy.tsx
  cypress/e2e/Simple.cy.ts
  package-lock.json
  package.json
  src/assets/download-emoji.png
  src/assets/neurobagel_data_dictionary.schema.json
  src/components/Download.tsx
  src/stores/data.test.ts
  src/stores/view.ts
  src/utils/mocks.ts
Labels: pr-minor

#65 [ENH] Implemented stepper
  cypress/component/ColumAnnotation.cy.tsx
  cypress/component/Landing.cy.tsx
  cypress/component/NavigationButton.cy.tsx
  cypress/component/Stepper.cy.tsx
  cypress/e2e/Simple.cy.ts
  src/App.tsx
  src/components/ColumnAnnotation.tsx
  src/components/Download.tsx
  src/components/Landing.tsx
  src/components/NavStepper.tsx
  src/components/NavigationButton.tsx
  src/components/Upload.tsx
  src/components/ValueAnnotation.tsx
  src/stores/view.test.ts
  src/stores/view.ts
  src/utils/constants.ts
  src/utils/types.ts
Labels: pr-minor

#71 [MNT] Replaced `Ramda` logic with `Immer`
  .eslintrc.cjs
  cypress/component/ColumnAnnotationCard.cy.tsx
  cypress/component/DescriptionEditor.cy.tsx
  package-lock.json
  package.json
  src/components/ColumnAnnotation.tsx
  src/components/ColumnAnnotationCard.tsx
  src/components/DataTablePreview.tsx
  src/components/DescriptionEditor.tsx
  src/components/Download.tsx
  src/stores/data.test.ts
  src/stores/data.ts
  src/utils/types.ts
Labels: pr-internal

#73 [MNT] Updated e2e test to cover current app functionalities
  cypress/component/CustomDataDictionaryPreview.cy.tsx
  cypress/component/DataDictionaryPreview.cy.tsx
  cypress/component/DataTablePreview.cy.tsx
  cypress/component/Download.cy.tsx
  cypress/component/FileUploader.cy.tsx
  cypress/component/NavStepper.cy.tsx
  cypress/component/UploadCard.cy.tsx
  cypress/e2e/Simple.cy.ts
  src/components/ColumnAnnotation.tsx
  src/components/CustomDataDictionaryPreview.tsx
  src/components/DataDictionaryPreview.tsx
  src/components/DataTablePreview.tsx
  src/components/Download.tsx
  src/components/FileUploader.tsx
  src/components/NavStepper.tsx
  src/components/Upload.tsx
  src/components/UploadCard.tsx
Labels: pr-internal

#82 [MNT] Update badges in README.md
  README.md
Labels: skip-release

#78 [ENH] Implemented the column navigation bar component for value annotation step
  cypress/component/Download.cy.tsx
  cypress/component/SideColumnNavbar.cy.tsx
  cypress/component/ValueAnnotation.cy.tsx
  src/components/Categorical.tsx
  src/components/ColumnAnnotation.tsx
  src/components/Continuous.tsx
  src/components/SideColumnNavBar.tsx
  src/components/Upload.tsx
  src/components/ValueAnnotation.tsx
  src/stores/data.test.ts
  src/utils/mocks.ts
Labels: pr-minor

#84 [ENH] Implemented `Categorical` component
  cypress/component/Categorical.cy.tsx
  cypress/component/DescriptionEditor.cy.tsx
  cypress/component/ValueAnnotation.cy.tsx
  src/components/Categorical.tsx
  src/components/ColumnAnnotationCard.tsx
  src/components/Continuous.tsx
  src/components/DescriptionEditor.tsx
  src/components/Download.tsx
  src/components/ValueAnnotation.tsx
  src/stores/data.test.ts
  src/stores/data.ts
  src/utils/types.ts
Labels: pr-minor

#88 [ENH] Implemented `Continuous` component and updated tests
  cypress/component/Categorical.cy.tsx
  cypress/component/Continuous.cy.tsx
  cypress/component/ValueAnnotation.cy.tsx
  cypress/e2e/MainUserFlow.cy.ts
  cypress/e2e/Simple.cy.ts
  src/components/ColumnAnnotationCard.tsx
  src/components/Continuous.tsx
  src/components/Download.tsx
  src/components/ValueAnnotation.tsx
  src/stores/data.test.ts
  src/stores/data.ts
  src/utils/types.ts
Labels: pr-minor, release

#93 [MNT] Updated `README.md`
  README.md
  cypress/e2e/MainUserFlow.cy.ts
  package-lock.json
  package.json
Labels: skip-release

#96 [FIX] Fixed the issue with shared state between Columns in `DescriptionEditor` of `Continuous` Component
  cypress/component/ValueAnnotation.cy.tsx
  cypress/e2e/MainUserFlow.cy.ts
  src/components/Continuous.tsx
Labels: pr-bug-fix

#101 [MNT] Set up tool to sort imports
  .prettierrc.json
  cypress.config.ts
  cypress/component/ValueAnnotation.cy.tsx
  cypress/support/component.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/Categorical.tsx
  src/components/ColumnAnnotation.tsx
  src/components/CustomDataDictionaryPreview.tsx
  src/components/DataTablePreview.tsx
  src/components/DescriptionEditor.tsx
  src/components/Download.tsx
  src/components/ErrorBoundary.tsx
  src/components/FileUploader.tsx
  src/components/Landing.tsx
  src/components/NavStepper.tsx
  src/components/SideColumnNavBar.tsx
  src/components/Upload.tsx
  src/components/UploadCard.tsx
  src/components/ValueAnnotation.tsx
  src/main.tsx
  src/stores/data.test.ts
  src/stores/data.ts
  src/stores/view.test.ts
  src/stores/view.ts
  src/utils/constants.ts
  vite.config.ts
Labels: skip-release

#102 [MNT] Implement custom hook for pagination and column updates
  src/components/Categorical.tsx
  src/components/ColumnAnnotation.tsx
  src/components/DataTablePreview.tsx
  src/hooks.ts
Labels: skip-release
