Repository neurobagel/annotation-tool, pull requests merged in 2025-09, with the labels that each got.

#233 [REF] Update fallback config to remove subjectGroup
  cypress/component/ValueAnnotation.cy.tsx
  cypress/e2e/MainUserFlow.cy.ts
  cypress/fixtures/examples/mock.json
  src/assets/default_config/config.json
  src/assets/default_config/diagnosis.json
  src/assets/default_config/subjectgroup.json
  src/utils/mocks.ts
  src/utils/util.ts
Labels: pr-internal

#238 [MNT] Implemented switch for displaying config card
  cypress/component/Upload.cy.tsx
  src/App.tsx
  src/components/Upload.tsx
  vite.config.ts
Labels: pr-patch, release

#239 [FIX] `configCard` visibility bug
  .github/workflows/tests.yaml
  cypress/component/Upload.cy.tsx
  src/components/Upload.tsx
Labels: pr-bug-fix, release

#275 Added instructions for different steps
  cypress/component/Instruction.cy.tsx
  src/components/ColumnAnnotation.tsx
  src/components/Instruction.tsx
  src/components/MultiColumnMeasures.tsx
  src/components/Upload.tsx
  src/components/ValueAnnotation.tsx
  src/utils/instructions.tsx
Labels: pr-patch

#292 [ENH] Prefixed assessment terms with abbreviations
  src/components/MultiColumnMeasuresCard.tsx
Labels: pr-patch
