Repository neurobagel/annotation-tool, pull requests merged in 2025-08, with the labels that each got.

#212 [ENH] Add App bar
  cypress/component/AppTitle.cy.tsx
  cypress/e2e/MainUserFlow.cy.ts
  src/App.tsx
  src/components/AppTitle.tsx
  src/components/ColumnAnnotation.tsx
Labels: pr-minor

#213 [ENH] Releasing `subject group` and `identifies` breaking change
  .github/workflows/tests.yaml
  CONFIGURATION.md
  cypress/component/AppTitle.cy.tsx
  cypress/component/ColumAnnotation.cy.tsx
  cypress/component/ColumnAnnotationCard.cy.tsx
  cypress/component/ValueAnnotation.cy.tsx
  cypress/component/ValueAnnotationTabs.cy.tsx
  cypress/e2e/MainUserFlow.cy.ts
  cypress/fixtures/examples/example_synthetic.json
  cypress/fixtures/examples/example_synthetic.tsv
  cypress/fixtures/examples/mock.json
  cypress/fixtures/examples/mock.tsv
  cypress/fixtures/examples/mock_with_empty_line.tsv
  src/App.tsx
  src/assets/default_config/config.json
  src/assets/default_config/subjectgroup.json
  src/assets/neurobagel_data_dictionary.schema.json
  src/components/AppTitle.tsx
  src/components/ColumnAnnotation.tsx
  src/components/ColumnAnnotationCard.tsx
  src/components/ColumnTypeCollapse.tsx
  src/components/Continuous.tsx
  src/components/Download.tsx
  src/components/MultiColumnMeasures.tsx
  src/components/ValueAnnotation.tsx
  src/components/ValueAnnotationTabs.tsx
  src/hooks.ts
  src/stores/data.test.ts
  src/stores/data.ts
  src/utils/constants.ts
  src/utils/external_types.ts
  src/utils/internal_types.ts
  src/utils/mocks.ts
  src/utils/util.test.ts
  src/utils/util.ts
Labels: release

#228 [FIX] nav-bar hidden behind top App bar
  cypress/e2e/MainUserFlow.cy.ts
  src/App.tsx
Labels: pr-bug-fix, release

#230 [MNT] Added a check for config files to the pull_request_template
  .github/pull_request_template.md
Labels: skip-release
